version: 2.1
orbs:
  # https://github.com/cypress-io/circleci-orb
  cypress: cypress-io/cypress@3

jobs:
  node-18:
    executor:
      name: cypress/default
      node-version: "18.16.1"
    steps:
      - cypress/run:
          post-install: npm run build
          start-command: npm start

workflows:
  build:
    jobs:
      # to run end-to-end tests in Electron browser
      - node-18:
          name: Electron test
          cypress-command: "npx wait-on@latest http://localhost:3003 && npx cypress run"

      # to run end-to-end tests in Firefox browser
      - node-18:
          name: Firefox test
          install-browsers: true
          cypress-command: "npx wait-on@latest http://localhost:3003 && npx cypress run --browser firefox"

      # wait for all jobs to finish and possible run NPM release
      - node-18:
          name: NPM release
          requires:
            - Electron test
            - Firefox test
          post-install: npm install
          start-command: echo 'Nothing to start in this job'
          install-command: echo 'Nothing to install in this job'
          # instead of "cypress run" do NPM release 😁
          cypress-command: npm run semantic-release

